# Quater 2: Class_1

## NUMPY:
* `Numerical python`
* used for numerical computations using arrays
* ndarray - an n-dimensional array 
* Linear Algebric operartions
* 

### Difference between an Array & List in python:
   * Array:
       * Faster
       * Contiguous memory Allocation
       * `Support vertorized operations`
       * Store same data type 
       * If you want to increase the size of array, recreate the array
       * It is easy to traverse through an array as all elements are stored in same location in memory
       
   * List:
       * Slower
       * Non contiguous memory Allocation (Sparse memory Allocation)
       * Store different data types
       * List has Dynamic size, it can grow 
       * Items are stored in different locations in memory and the list has to remember address of each item.
       * It is difficult to traverse through a list as elements might be stored at different locations in memory.
       

# A comparison of Array Vs. List in Python:

`%time` is used to find the total time taken to execute operation in a cell.

`wall time = Execution time`

In [9]:
import numpy as np

In [13]:
list1 = range(1000000) # starts from 1
print(list1)

range(0, 1000000)


In [14]:
array1 = np.arange(1000000) # starts from 0
print(array1)

[     0      1      2 ... 999997 999998 999999]


# --> multiply list1 with 5:

In [18]:
results= []
for i in list1:
     results.append(i*5)
    
print(results)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



# list comprehension:

In [19]:
results = [i * 5 for i in list1] ; results


[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 8

##  Time comparison in lists

In [ ]:
%time for i in range(100): results=  [i * 5 for i in list1]

# --> multiply array1 with 5:

In [20]:
array1 * 5 

array([      0,       5,      10, ..., 4999985, 4999990, 4999995])

In [21]:
%time array1* 5

CPU times: total: 0 ns
Wall time: 1.99 ms


array([      0,       5,      10, ..., 4999985, 4999990, 4999995])

##  Time comparison in arrays

In [24]:
%time for i in range(100): result = array1 * 5 

CPU times: total: 281 ms
Wall time: 270 ms


In [25]:
print(result)

[      0       5      10 ... 4999985 4999990 4999995]


### So, we can see that list is slower than array

# Numpy array creation methods:
* np.array()
* np.zeros()
* np.ones()
* np.empty()
* np.arange()

### 1-D Array (One Dimensional array)

In [26]:
my_array = np.zeros((10))
my_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
my_array1 = np.ones((15))
my_array1 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### we can now make array of any number using np.zeros & np.ones array as:

## ==> by using np.zeros()

* to make array of 2

In [28]:
x = np.zeros((10))
x = x + 2
x

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

### OR:

In [29]:
x = np.zeros((10)) + 2
x

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

* to make array of 8:

In [30]:
x = np.zeros((10)) + 8
x

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

## ==> by using np.ones()

In [31]:
y = np.ones(10) 
y = y + 1
y

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

### OR

In [32]:
y = np.ones(10) + 1
y

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

# shape of an array:
* 1D = np.zeros(n)
* 2D = np.zeros((each_row,each_column))
* 3D = np.zeros((depth,each_row,each_column))

In [33]:
a = np.zeros(50)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
b = np.zeros((10,6))
b

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [35]:
c = np.zeros((3,2,6))
c

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

### To find the shape of the array: 
`.shape`

In [36]:
c.shape

(3, 2, 6)

# Empty array: `np.empty(( ))`

In [161]:
empty_arr = np.empty((9,9))
empty_arr

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        6.95187281e-310, 1.63041663e-322, 1.17378282e-311,
        1.17379703e-311, 1.17373741e-311, 1.17377982e-311],
       [0.00000000e+000, 1.17377081e-311, 0.00000000e+000,
        0.00000000e+000, 1.17373741e-311, 0.00000000e+000,
        4.24399159e-314, 1.08646184e-311, 4.32887141e-312],
       [1.17346367e-311, 1.17373741e-311, 1.17373741e-311,
        1.17373741e-311, 1.17373741e-311, 1.17373741e-311,
        1.17373741e-311, 1.17373730e-311, 1.17373741e-311],
       [1.17373741e-311, 1.17373741e-311, 1.17373741e-311,
        1.17373741e-311, 1.17373726e-311, 1.17373741e-311,
        1.17373741e-311, 1.17373741e-311, 1.17373741e-311],
       [1.17373741e-311, 1.17373741e-311, 1.17373741e-311,
        1.17373741e-311, 1.17373741e-311, 1.17373741e-311,
        1.17373737e-311, 1.17373741e-311, 1.17373738e-311],
       [1.17373741e-311, 1.17373736e-311, 6.95187282e-310,
        1.17380244e-311, 1.17380988e-311, 0.0000000

In [37]:
e = np.empty(0)
e

array([], dtype=float64)

# we can't add elements at runtime in arrays

# Attributes of Numpy array:

* `shape` : a tuple indicating the size of each dimension
* `dtype` : data type of the array
* `ndim`  : number of dimensions of the array

### Array of custom elements:

In [38]:
arr = np.array([1,3,54,67,98,34,23,70])
arr

array([ 1,  3, 54, 67, 98, 34, 23, 70])

In [39]:
arr.shape

(8,)

In [40]:
arr.ndim

1

In [41]:
arr = arr.reshape(4,2)

In [42]:
arr.shape

(4, 2)

In [43]:
arr

array([[ 1,  3],
       [54, 67],
       [98, 34],
       [23, 70]])

In [44]:
arr.ndim

2

In [45]:
arr.dtype

dtype('int32')

# accessing indivisual elements of an array:

In [46]:
 arr

array([[ 1,  3],
       [54, 67],
       [98, 34],
       [23, 70]])

In [47]:
#34
arr[2,1]

34

In [48]:
#23
arr[3,0]

23

In [49]:
#67
arr[1,1]

67

In [50]:
arr.ndim

2

### reshape arr into 3D array & practice how to access indivisual elements of an array:

In [51]:
arr.reshape((2,2,2))

array([[[ 1,  3],
        [54, 67]],

       [[98, 34],
        [23, 70]]])

# Slicing:
* start (included)
* end   (excluded)
* step  (sequence, gap)

In [52]:
arr.shape

(4, 2)

In [53]:
arr


array([[ 1,  3],
       [54, 67],
       [98, 34],
       [23, 70]])

In [54]:
arr[0:3]

array([[ 1,  3],
       [54, 67],
       [98, 34]])

 ## we can use slicing & indexing..

In [55]:
arr

array([[ 1,  3],
       [54, 67],
       [98, 34],
       [23, 70]])

In [56]:
arr[0:4,0] # starting from row 0 to row 3 as end is excluded & 0th indexed column of the slicing!

array([ 1, 54, 98, 23])

In [57]:
 arr[0:3,1] # starting from row 0 to row 2 as end is excluded & 1st indexed column of the slicing!

array([ 3, 67, 34])

In [58]:
arr

array([[ 1,  3],
       [54, 67],
       [98, 34],
       [23, 70]])

## Indexing in 3D array:

In [68]:
arr.reshape(2,2,2)

array([[[ 1,  3],
        [54, 67]],

       [[98, 34],
        [23, 70]]])

In [71]:
arr[0:4]

array([[ 1,  3],
       [54, 67],
       [98, 34],
       [23, 70]])

In [72]:
arr[0:2]

array([[ 1,  3],
       [54, 67]])

In [73]:
#3
arr[0,1]

3

In [75]:
#98
arr[2,0]

98

In [76]:
#70
arr[3,1]

70

In [77]:
#67
arr[1,1]

67

# Row Wise:

In [59]:
arr[::2] # (Row wise) step size is 2 so 0th and 2nd row will be displayed

array([[ 1,  3],
       [98, 34]])

# Column wise:

In [1]:
arr[::2,1] # (Column wise) step size is 2 so 0th and 2nd row will be displayed

NameError: name 'arr' is not defined

# fancy indexing:
* only pass the index number of the required values as `array[ [i1,i2,i3...in] ]` where i = index number
* array[ [required indexes] ]

In [61]:
arr.ndim

2

In [62]:
arr  # arr is 2D array

array([[ 1,  3],
       [54, 67],
       [98, 34],
       [23, 70]])

In [63]:
j =arr.reshape(8) # converting into 1D array

In [64]:
j

array([ 1,  3, 54, 67, 98, 34, 23, 70])

In [65]:
j[[2,4,5,7]]

array([54, 98, 34, 70])

In [66]:
arr

array([[ 1,  3],
       [54, 67],
       [98, 34],
       [23, 70]])

In [78]:
arr[::,0]

array([ 1, 54, 98, 23])

In [79]:
arr[::,1]

array([ 3, 67, 34, 70])

# fancy indexing:
* only pass the index number of the required values as `array[ [i1,i2,i3...in] ]` where i = index number

In [82]:
arr.ndim


2

In [83]:
arr.reshape(8)

array([ 1,  3, 54, 67, 98, 34, 23, 70])

In [87]:
arr.ndim

2

In [101]:
k =arr.reshape(8)

In [102]:
k.ndim

1

In [103]:
k.shape

(8,)

In [104]:
# 98 70
k[[4,7]]

array([98, 70])

In [106]:
# 3 67 34 23 

k[[1,3,5,6]]

array([ 3, 67, 34, 23])

# Vectorized operations:

* to create a custom array: `np.array([comma sperated elements])` 
* ALL the operations will be performed element wise
* it is much more faster in numpy arrays as compared to list operations

In [110]:
x = np.array([1,7,3])
y = np.array([5,2,8])

In [111]:
x + y

array([ 6,  9, 11])

In [112]:
x - y

array([-4,  5, -5])

In [113]:
x * y

array([ 5, 14, 24])

In [114]:
x / y

array([0.2  , 3.5  , 0.375])

In [115]:
1/x


array([1.        , 0.14285714, 0.33333333])

In [116]:
1/y

array([0.2  , 0.5  , 0.125])

In [118]:
x * y

array([ 5, 14, 24])

In [117]:
x*y**2

array([ 25,  28, 192])

# Shapes:

###### 00000
###### 11111
###### 11111
###### 11111
###### 00000

In [119]:
a = np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [124]:
a[0]= 0
a[-1]= 0 

In [125]:
a

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

###### 00000
###### 01110
###### 01110
###### 01110
###### 00000

In [130]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [131]:
a[1] = 1
a[2] = 1
a[3] = 1

In [132]:
a

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [133]:
a[1,0] = 0
a[2,0] = 0
a[3,0] = 0
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [134]:
a[1,4] = 0
a[2,4] = 0
a[3,4] = 0
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

# it is the required shape

In [136]:
a 


array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

## OR , smarter approach

In [137]:
b = np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [138]:
b[1:-1, 1:-1] = 1
b

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

# Checkerboard pattern:

In [154]:
chkboard = np.ones((5,5))
chkboard

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [156]:
chkboard[0,1] = 0
chkboard[0,3] = 0
chkboard[1,0] = 0
chkboard[1,2] = 0
chkboard[1,4] = 0
chkboard[2,1] = 0
chkboard[2,3] = 0
chkboard[3,0] = 0
chkboard[3,2] = 0
chkboard[3,4] = 0
chkboard[4,1] = 0
chkboard[4,3] = 0


chkboard

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

# Football ground:

In [139]:
football_ground = np.zeros((10,10))
football_ground

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [140]:
football_ground[::2]= 1
football_ground

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [141]:
football_ground = np.ones((10,10))
football_ground

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [142]:
football_ground[::2]= 0
football_ground

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# comparison between metrices:


In [162]:
salary = np.array([100,540,220,560,340,260,1100])


In [163]:
salary

array([ 100,  540,  220,  560,  340,  260, 1100])

In [164]:
salary > 500

array([False,  True, False,  True, False, False,  True])

# for getting the values instead of True/False:

In [165]:
salary [salary > 500]

array([ 540,  560, 1100])

# Try all functions of array: