# Class2_Numpy

* We can't do vectorized opertions on lists and also we have to use loops for doing basic calculations.

In [3]:
a = np.array([1,5,8])
b = np.array([2,3,6])
a+b

array([ 3,  8, 14])

### But in lists:

In [4]:
a = [1,5,8]
b = [2,3,6]

a+b # it will concatinate the both lists..

[1, 5, 8, 2, 3, 6]

# Use of enumerate funtion:

In [5]:
#to add both lists we will use loops:
sum = []
for i,e in enumerate(a):
    sum.append(a[i]+b[i])
    
print(sum)

[3, 8, 14]


# ==> where funtion in numpy:

   * `np.where(condition, option A, option B)`

In [1]:
import numpy as np

In [4]:
Marks = np.array([29,54,76,34,21,58,24,64])
m = np.where(Marks >= 50, "Pass", "Fail")


In [5]:
m

array(['Fail', 'Pass', 'Pass', 'Fail', 'Fail', 'Pass', 'Fail', 'Pass'],
      dtype='<U4')

In [9]:
salary = np.array([20,65,23,86,50,76,])
incremented_salary = np.where(salary <50, salary*5.0, salary*2.5)


In [10]:
incremented_salary

array([100. , 162.5, 115. , 215. , 125. , 190. ])

In [11]:
incremented_salary.dtype

dtype('float64')

# Transpose of an array:
* changing rows into columns
* `array.T` OR `array.transpose()`

In [17]:
arr = np.arange(1,101).reshape((10,10))

In [13]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [18]:
arr.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [19]:
arr.transpose()

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

# Mathematical & statistical methods in array: 
* Mean = `array.mean()` add all number and divide by total number.
* Cumsum = `array.cumsum()` add previous number with the next one. 
* Cumprod = `array.cumprod()` multiply previous number with the next one.

In [20]:
arr = np.array([1,4,6,7,2,5])
arr.mean()

4.166666666666667

In [21]:
arr.cumsum() 

array([ 1,  5, 11, 18, 20, 25], dtype=int32)

In [22]:
arr.cumprod()

array([   1,    4,   24,  168,  336, 1680], dtype=int32)

# Procedure Vs. Function:
* Procedures don't return any value
* Function return any value
* Function made within class can be called a Method.

# Mehtods for boolean array:
* array.any()
* array.all()

In [8]:
gender = np.array(['Male', 'Female', 'Male', 'Male', 'Female', 'Male'])


In [9]:
gender

array(['Male', 'Female', 'Male', 'Male', 'Female', 'Male'], dtype='<U6')

In [15]:
a = gender == 'Male'
a

array([ True, False,  True,  True, False,  True])

In [11]:
gender[gender == 'Male']

array(['Male', 'Male', 'Male', 'Male'], dtype='<U6')

In [26]:
a.sum() #.sum function is simply adding the boolean values stored in variable 'a'.

4

In [23]:
b = gender == 'Female'

In [24]:
b

array([False,  True, False, False,  True, False])

In [22]:
gender[gender == 'Female']

array(['Female', 'Female'], dtype='<U6')

In [27]:
b.sum() #.sum function is simply adding the boolean values stored in variable 'b'.

2

# -> array.any():
* it is used to tell if there is any true value in the variable or not.
* it will work only on boolean 

# -> array.all():
* it will be true if all values of a variable is true.
* it will work only on boolean 

#### Let's apply any() function on our previous variables of Male and Female data.

In [28]:
a.any()

True

In [29]:
b.any()

True

In [30]:
a.all()

False

In [49]:
# let's make another np array with all true values:
gender_male = np.array(['Male','Male', 'Male', 'Male'])

In [50]:
gender_male

array(['Male', 'Male', 'Male', 'Male'], dtype='<U4')

In [51]:
gender_male == "Male"

array([ True,  True,  True,  True])

In [45]:
gender_m

array([ True,  True,  True,  True])

In [56]:
gender_m.any() # to find if there is any true value.

True

In [59]:
gender_m.all() # to find out if all values are true.

True

In [58]:
gender_m.sum() # to find how many true values we have in our vairable.

4

In [60]:
arr = np.array([2,5,7,8,9])
x = arr%2 == 0

In [61]:
x

array([ True, False, False,  True, False])

In [63]:
arr[arr%2 == 0] # to get the exact true values.

array([2, 8])

In [64]:
x.sum() # it means the sum of true values is 2. so we've 2 true values.

2

In [65]:
x.any() # to find if there is any true value.

True

In [66]:
x.all() # to find out if all values are true.

False

# Universal Quantifier:
* check if all the values exit.
# Existantial Quantifier:
* check if any one value exist.

# .sort()

In [84]:
arr1 = np.array([1,6,3,6,2,15,7,4,2])

In [85]:
arr1.sort()

In [86]:
arr1

array([ 1,  2,  2,  3,  4,  6,  6,  7, 15])

In [87]:
arr1.sort() # inplace

In [88]:
arr1[::-1]

array([15,  7,  6,  6,  4,  3,  2,  2,  1])

# arr.unique():
* it is used to get the unique values (not repeated values)

In [90]:
np.unique(arr1)  

array([ 1,  2,  3,  4,  6,  7, 15])

In [92]:
a = np.unique(arr1)  

# File Input Output:

* `np.save()` is used to save an array in a file. <br>
    * syntax : `np.save("filename", array)` <br>
        * it's extension is `.npy`

* `np.load()` is used to load the save file. <br>
     * syntax : `np.load("filename.extension")` <br>
         * it's important to write extension with file name.

* `np.savez()` is used to save multiple arrays in a file. <br>
    
    * syntax : `np.savez("filename", kwrg1=arr1 , kwrg2=arr2)`
        * it's extension is `.npz`
            

# => save array

In [93]:
np.save("data", a) # the file is saved in the current directory

# => load array

In [95]:
content = np.load("data.npy")

In [96]:
content

array([ 1,  2,  3,  4,  6,  7, 15])

# => saving multiple arrays:

In [97]:
students = np.array(['ali', 'ahmed', 'subhan'])
marks    = np.array([30 , 24 , 65])

In [98]:
np.savez("arrays", stu= students, m= marks) #stu & m are keyword arguments

### * we can't view the saved data in normal file but we can use the saved numpy data in our notebooks for further procesing

# => load array

In [3]:
np.load("arrays.npz")

In [4]:
results = np.load("arrays.npz") 

In [5]:
results

In [106]:
results["stu"] # it works like a dictionary where we use keys to get the respective values.

array(['ali', 'ahmed', 'subhan'], dtype='<U6')

In [107]:
results["m"]

array([30, 24, 65])

# Linear Algebra operations: